services:
  web:
    build:
      context: .
    command: gunicorn --bind 0.0.0.0:8000 S100Registry.wsgi:application  
    volumes:
      - /home/bluemap/media:/usr/src/app/files
      - /home/bluemap/static:/usr/src/app/_static
    expose:
      - "8000"
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "21803:80"  
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  
      - /home/bluemap/media:/usr/src/app/files
      - /home/bluemap/static:/usr/src/app/_static
    depends_on:
      - web
    restart: always 