from mongo_driver import db

RegistryAccess = db['RegistryAccess']


### concept registry
S100_CD_AttributeConstraints = db['S100_CD_AttributeConstraints']
S100_CD_AttributeUsage = db['S100_CD_AttributeUsage']
S100_Concept_Item = db['S100_Concept_Item']
S100_Concept_ManagementInfo = db['S100_Concept_ManagementInfo']
S100_Concept_Reference = db['S100_Concept_Reference']
S100_Concept_ReferenceSource = db['S100_Concept_ReferenceSource']
S100_Concept_Register = db['S100_Concept_Register']
S100_DD_associatedAttribute = db['S100_DD_associatedAttribute']
S100_DD_distinction = db['S100_DD_distinction']

### portrayal registry
S100_PR_ColourToken_Association = db['S100_PR_ColourToken_Association']
S100_PR_Symbol_Association = db["S100_PR_Symbol_Association"]
S100_PR_Icon_Association = db["S100_PR_Icon_Association"]
S100_PR_ItemSchema_Association = db["S100_PR_ItemSchema_Association"]
S100_PR_Value_Association = db["S100_PR_Value_Association"]
S100_PR_Palette_Association = db["S100_PR_Palette_Association"]
S100_PR_DisplayMode_Association = db["S100_PR_DisplayMode_Association"]
S100_PR_ViewingGroup_Association = db["S100_PR_ViewingGroup_Association"]
S100_PR_Highlight_Association = db["S100_PR_Highlight_Association"]
S100_PR_Message_Association = db["S100_PR_Message_Association"]

S100_Portrayal_Alert = db['S100_Portrayal_Alert']
S100_Portrayal_AlertHighlight = db['S100_Portrayal_AlertHighlight']
S100_Portrayal_AlertInfo = db['S100_Portrayal_AlertInfo']
S100_Portrayal_AlertMessage = db['S100_Portrayal_AlertMessage']
S100_Portrayal_AlertPriority = db['S100_Portrayal_AlertPriority']
S100_Portrayal_AreaFill = db['S100_Portrayal_AreaFill']
S100_Portrayal_AreaFillSchema = db['S100_Portrayal_AreaFillSchema']
S100_Portrayal_CIEValue = db['S100_Portrayal_CIEValue']
S100_Portrayal_ColourPalette = db['S100_Portrayal_ColourPalette']
S100_Portrayal_ColourProfileSchema = db['S100_Portrayal_ColourProfileSchema']
S100_Portrayal_ColourToken = db['S100_Portrayal_ColourToken']
S100_Portrayal_ContextParameter = db['S100_Portrayal_ContextParameter']
S100_Portrayal_DisplayMode = db['S100_Portrayal_DisplayMode']
S100_Portrayal_DisplayPlane = db['S100_Portrayal_DisplayPlane']
S100_Portrayal_DrawingPriority = db['S100_Portrayal_DrawingPriority']
S100_Portrayal_Font = db['S100_Portrayal_Font']
S100_Portrayal_LineStyle = db['S100_Portrayal_LineStyle']
S100_Portrayal_LineStyleSchema = db['S100_Portrayal_LineStyleSchema']
S100_Portrayal_NationalLanguageString = db['S100_Portrayal_NationalLanguageString']
S100_Portrayal_PaletteItem = db['S100_Portrayal_PaletteItem']
S100_Portrayal_Pixmap = db['S100_Portrayal_Pixmap']
S100_Portrayal_PixmapSchema = db['S100_Portrayal_PixmapSchema']
S100_Portrayal_SRGBValue = db['S100_Portrayal_SRGBValue']
S100_Portrayal_Symbol = db['S100_Portrayal_Symbol']
S100_Portrayal_SymbolSchema = db['S100_Portrayal_SymbolSchema']
S100_Portrayal_ViewingGroup = db['S100_Portrayal_ViewingGroup']
S100_Portrayal_ViewingGroupLayer = db['S100_Portrayal_ViewingGroupLayer']
