# Generated by Django 4.2.10 on 2024-02-13 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='S100_RE_Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('operatingLanguage', models.CharField(max_length=100)),
                ('contentSummary', models.TextField()),
                ('uniformResourceIdentifier', models.CharField(max_length=100)),
                ('dateOfLastChange', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='S100_RE_RegisterItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemIdentifier', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('definition', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('itemStatus', models.CharField(choices=[('processing', 'processing'), ('valid', 'valid'), ('superseded', 'superseded'), ('notValid', 'notValid'), ('retired', 'retired'), ('clarified', 'clarified')], max_length=50)),
                ('alias', models.JSONField(default=list, null=True)),
                ('camelCase', models.CharField(blank=True, max_length=100, null=True)),
                ('definitionSource', models.CharField(blank=True, max_length=100, null=True)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('similarityToSource', models.CharField(blank=True, max_length=100, null=True)),
                ('justification', models.CharField(blank=True, max_length=100, null=True)),
                ('proposedChange', models.CharField(blank=True, max_length=100, null=True)),
                ('s100_RE_Register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regiSystem.s100_re_register')),
            ],
        ),
        migrations.CreateModel(
            name='S100_RE_ReferenceSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referenceldentifier', models.CharField(blank=True, max_length=100, null=True)),
                ('sourceDocument', models.CharField(max_length=100)),
                ('s100_RE_RegisterItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regiSystem.s100_re_registeritem')),
            ],
        ),
        migrations.CreateModel(
            name='S100_RE_Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referenceldentifier', models.CharField(blank=True, max_length=100, null=True)),
                ('sourceDocument', models.CharField(max_length=100)),
                ('similarity', models.CharField(choices=[('identical', 'identical'), ('restyled', 'restyled'), ('contextAdded', 'contextAdded'), ('generalization', 'generalization'), ('specialization', 'specialization'), ('unspecified', 'unspecified')], max_length=100)),
                ('s100_RE_RegisterItem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='regiSystem.s100_re_registeritem')),
            ],
        ),
        migrations.CreateModel(
            name='S100_RE_ManagementInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposalType', models.CharField(choices=[('addition', 'addition'), ('clarification', 'clarification'), ('supersession', 'supersession'), ('retirement', 'retirement')], max_length=100)),
                ('submittingOrganisation', models.CharField(max_length=100)),
                ('proposedChange', models.CharField(max_length=100)),
                ('dateAccepted', models.DateField(null=True)),
                ('dateProposed', models.DateField()),
                ('dateAmended', models.DateField()),
                ('proposalStatus', models.CharField(choices=[('notYetDetermined', 'notYetDetermined'), ('transferred', 'transferred'), ('accepted', 'accepted'), ('rejected', 'rejected'), ('withdrawn', 'withdrawn'), ('negotiation', 'negotiation'), ('appeal', 'appeal'), ('appealTransferred', 'appealTransferred'), ('appealAccepted', 'appealAccepted'), ('appealRejected', 'appealRejected')], max_length=100)),
                ('controlBodyNotes', models.JSONField(default=list, null=True)),
                ('s100_RE_RegisterItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regiSystem.s100_re_registeritem')),
            ],
        ),
    ]
