# Generated by Django 4.2.10 on 2024-02-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='S100_RE_RegisterItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemIdentifier', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('definition', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('itemStatus', models.CharField(max_length=50)),
                ('camelCase', models.CharField(blank=True, max_length=100, null=True)),
                ('definitionSource', models.CharField(blank=True, max_length=100, null=True)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('similarityToSource', models.CharField(blank=True, max_length=100, null=True)),
                ('justification', models.CharField(blank=True, max_length=100, null=True)),
                ('proposedChange', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
